# Generated by Django 4.2.5 on 2023-09-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('studentCode', models.TextField(blank=True)),
                ('faculty', models.TextField(blank=True)),
                ('major', models.TextField(blank=True)),
                ('semester', models.TextField(blank=True)),
            ],
        ),
    ]
