# Generated by Django 4.2.5 on 2023-09-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateApplicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='faculty',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='lastName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='major',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='semester',
            field=models.IntegerField(blank=True),
        ),
    ]
