# Generated by Django 4.2.5 on 2023-09-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateApplicant', '0005_alter_applicant_email_alter_applicant_studentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
    ]
