# Generated by Django 4.2.5 on 2023-09-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateApplicant', '0006_alter_applicant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=40, unique=True),
        ),
    ]
