# Generated by Django 4.2.7 on 2023-11-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', 'defaultData'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipannouncements',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
