# Generated by Django 4.2.5 on 2023-09-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('donor', models.CharField(max_length=100)),
                ('coverage', models.DecimalField(decimal_places=3, max_digits=7)),
                ('type', models.IntegerField()),
                ('requirements', models.TimeField(blank=True)),
            ],
        ),
    ]
