# Generated by Django 4.2.5 on 2023-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='coverage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scholarships',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
