# Generated by Django 4.2.5 on 2023-10-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantstatecheck',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantstatecheck',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
