# Generated by Django 4.2.7 on 2023-11-27 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0001_alter_scholarshipannouncements_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantstatecheck',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 23, 12, 26, 751029)),
        ),
    ]
