# Generated by Django 4.2.5 on 2023-10-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='type',
            field=models.IntegerField(choices=[(0, 'Intercambio'), (1, 'Rescate'), (2, 'Sustento')]),
        ),
    ]
