# Generated by Django 4.2.5 on 2023-11-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/photos'),
        ),
    ]
