# Generated by Django 4.2.5 on 2023-11-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='idDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
