# Generated by Django 4.2.5 on 2023-10-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0002_applicantstatecheck_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
