# Generated by Django 4.2.7 on 2023-11-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0002_applicantstatecheck'),
        ('ScholarshipModule', 'defaultData'),
    ]

    operations = [
    ]
