# Generated by Django 4.2.5 on 2023-11-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0002_alter_applicant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementandapplicant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
