# Generated by Django 4.2.5 on 2023-09-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0002_alter_scholarships_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='ID',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
