# Generated by Django 4.2.5 on 2023-11-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0002_scholarships_iddeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarships',
            old_name='idDeleted',
            new_name='isDeleted',
        ),
    ]
