# Generated by Django 4.2.5 on 2023-10-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0003_applicant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
