# Generated by Django 4.2.5 on 2023-10-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0003_rename_id_announcementandapplicant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
