# Generated by Django 4.2.5 on 2023-11-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0004_scholarsiptypes_remove_scholarships_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='coverage',
        ),
    ]
