# Generated by Django 4.2.5 on 2023-09-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0004_alter_scholarships_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('studentId', models.IntegerField()),
                ('scholarshipId', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='scholarships',
            name='ID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='AnnouncementType',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.TextField()),
                ('ScholarshipAnnouncementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnnouncementId', to='ScholarshipModule.announcements')),
            ],
        ),
    ]
