# Generated by Django 4.2.5 on 2023-09-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0005_donors_alter_scholarships_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='ID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
