# Generated by Django 4.2.5 on 2023-09-26 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0005_announcements_alter_scholarships_id_announcementtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementEvent',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('startingDate', models.DateField()),
                ('endDate', models.DateField()),
                ('type', models.IntegerField(choices=[(0, 'Inscripciones'), (1, 'Seleccion'), (2, 'Entrevistas'), (3, 'Publicacion')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementsStudents',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipAnnouncements',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='scholarshipId',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='studentId',
        ),
        migrations.AddField(
            model_name='announcements',
            name='type',
            field=models.IntegerField(choices=[(0, 'Abierta'), (1, 'Cerreada'), (2, 'Mixta')], default=1),
        ),
        migrations.DeleteModel(
            name='AnnouncementType',
        ),
        migrations.AddField(
            model_name='scholarshipannouncements',
            name='announcementId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnnouncementId1', to='ScholarshipModule.announcements'),
        ),
        migrations.AddField(
            model_name='scholarshipannouncements',
            name='scholarshipId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScholarshipId1', to='ScholarshipModule.scholarships'),
        ),
        migrations.AddField(
            model_name='announcementsstudents',
            name='announcementId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnnouncementId2', to='ScholarshipModule.announcements'),
        ),
        migrations.AddField(
            model_name='announcementsstudents',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentId2', to='ScholarshipModule.students'),
        ),
        migrations.AddField(
            model_name='announcementevent',
            name='AnnouncementId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnnouncementId3', to='ScholarshipModule.announcements'),
        ),
    ]
