# Generated by Django 4.2.5 on 2023-11-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0006_scholarsiptypes_id_alter_scholarsiptypes_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarsiptypes',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_Scholarship', to='ScholarshipModule.scholarships'),
        ),
    ]
