# Generated by Django 4.2.5 on 2023-09-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0006_remove_user_email_remove_user_phone_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
