# Generated by Django 4.2.5 on 2023-09-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0007_alter_announcementevent_announcementid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementevent',
            name='AnnouncementId',
        ),
        migrations.AlterField(
            model_name='announcementevent',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Inscripciones'), (1, 'Seleccion'), (2, 'Entrevistas'), (3, 'Publicacion')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='announcementsstudents',
            name='announcementId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnnouncementId2', to='ScholarshipModule.announcements'),
        ),
        migrations.AlterField(
            model_name='scholarshipannouncements',
            name='announcementId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnnouncementId1', to='ScholarshipModule.announcements'),
        ),
        migrations.AddField(
            model_name='announcementevent',
            name='announcementId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnnouncementId3', to='ScholarshipModule.announcements'),
        ),
    ]
