# Generated by Django 4.2.5 on 2023-09-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0007_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
