# Generated by Django 4.2.5 on 2023-09-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0007_alter_donors_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholarships',
        ),
    ]
