# Generated by Django 4.2.5 on 2023-09-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0005_alter_scholarships_id'),
        ('ScholarshipModule', '0010_alter_user_managers_alter_user_name'),
    ]

    operations = [
    ]
