# Generated by Django 4.2.5 on 2023-09-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0009_scholarships'),
        ('ScholarshipModule', '0010_alter_user_managers_alter_user_name'),
    ]

    operations = [
    ]
