# Generated by Django 4.2.5 on 2023-09-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0011_merge_20230926_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('studentCode', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=30)),
                ('career', models.CharField(max_length=30)),
                ('semester', models.IntegerField(blank=True)),
                ('email', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
