# Generated by Django 4.2.5 on 2023-09-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0013_applicant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='status',
        ),
    ]
