# Generated by Django 4.2.5 on 2023-09-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0014_remove_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.IntegerField(choices=[(0, 'En revisión'), (1, 'Beneficiario'), (2, 'No aceptado')], default=0),
        ),
    ]
