# Generated by Django 4.2.5 on 2023-10-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0015_applicant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='announcement',
        ),
    ]
