# Generated by Django 4.2.5 on 2023-09-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0012_applicant'),
        ('ScholarshipModule', '0015_applicant_status'),
    ]

    operations = [
    ]
