# Generated by Django 4.2.5 on 2023-09-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0016_merge_0012_applicant_0015_applicant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='career',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='school',
        ),
        migrations.AddField(
            model_name='applicant',
            name='announcement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_announcement', to='ScholarshipModule.announcement'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='faculty',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='major',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.IntegerField(choices=[(0, 'En revisión'), (1, 'Beneficiario'), (2, 'No aceptado')], default=0),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='studentCode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
