# Generated by Django 4.2.5 on 2023-10-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarshipModule', '0016_remove_applicant_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementAndApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_announcement', to='ScholarshipModule.announcement')),
                ('applicantID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_applicant', to='ScholarshipModule.applicant')),
            ],
        ),
    ]
